import React, { useState, useEffect } from 'react';
import Canvas from './components/Canvas';
import PrivateKeyArt from './PrivateKeyArt';
import { Wallet } from 'ethers';
import './App.css';

function App() {
  const [drawing, setDrawing] = useState(new PrivateKeyArt());
  const [privateKey, setPrivateKey] = useState('');
  const [ethAddress, setEthAddress] = useState('');

  useEffect(() => {
    setPrivateKey(drawing.toPrivateKey());
  }, [drawing]);

  useEffect(() => {
    if (privateKey && /^[0-9a-fA-F]{64}$/i.test(privateKey) && privateKey !== '0'.repeat(64)) {
      const wallet = new Wallet('0x' + privateKey);
      setEthAddress(wallet.address);
    }
  }, [privateKey]);

  const clearCanvas = () => {
    const newDrawing = new PrivateKeyArt();
    setDrawing(newDrawing);
  };

  const invertCanvas = () => {
    drawing.invert();
    setDrawing(new PrivateKeyArt(drawing.toPrivateKey()));
  };

  const handlePrivateKeyChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newPrivateKey = event.target.value;
    setPrivateKey(newPrivateKey);
    const newDrawing = new PrivateKeyArt(newPrivateKey);
    setDrawing(newDrawing);
  };

  return (
    <div className="App">
      <h1>Pixel Key</h1>
      <p>
        Generate an Ethereum private key from pixel art<sup>*</sup>.
      </p>
      <Canvas drawing={drawing} setDrawing={setDrawing} scale={16} />
      <div className="button-container">
        <button onClick={invertCanvas}>Invert</button>
        <button onClick={clearCanvas}>Clear</button>
      </div>
      Private Key:
      <div className="input-container">
        <input type="text" value={`0x${privateKey}`} onChange={handlePrivateKeyChange} className="private-key-input" />
        <span onClick={() => navigator.clipboard.writeText(`0x${privateKey}`)} className="copy-icon" title="Copy">
          📄
        </span>
      </div>
      <div className="input-container">
        Address: {ethAddress}
        <span onClick={() => navigator.clipboard.writeText(ethAddress)} className="copy-icon" title="Copy">
          📄
        </span>
      </div>
      <div className="disclaimer">
        <p>
          <sup>*</sup> This is a toy project. Do not use any private keys generated by this website for anything
          important.
        </p>
      </div>
    </div>
  );
}

export default App;
